{% set name = "google-cloud-speech" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-speech-{{ version }}.tar.gz
  sha256: cb4911f567205a96490353cb71edca7a58b6d75f1924257101faeabd52071840

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4
    - google-api-core-grpc >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0

test:
  imports:
    - google.cloud.speech
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-speech
  summary: Google Cloud Speech API client library
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/googleapis/python-speech
  doc_url: https://googleapis.dev/python/speech/latest/index.html

extra:
  recipe-maintainers:
    - xylar
