{% set name = "google-cloud-speech" %}
{% set version = "2.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-speech-{{ version }}.tar.gz
  sha256: 2dbda8576afb084d6a73989ac731a9226df164aa6c391c753687e48e7a3ac4db

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - google-api-core-grpc >=1.32.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*
    - proto-plus >=1.22.0,<2.0.0dev
    - protobuf >=3.19.5,<5.0.0dev,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - google.cloud.speech
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-speech
  summary: Google Cloud Speech API client library
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/googleapis/python-speech
  doc_url: https://googleapis.dev/python/speech/latest/index.html

extra:
  recipe-maintainers:
    - xylar
